services:
  app:
    image: hexaprojetweb.azurecr.io/hexagone-web-projet:latest
    ports:
      - "8000:80"
    volumes:
      - uploads:/var/www/html/uploads

  mysql:
    image: hexaprojetweb.azurecr.io/mysql:latest
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: app_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass

  phpmyadmin:
    image: hexaprojetweb.azurecr.io/phpmyadmin:latest
    links:
      - "mysql"
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1

volumes:
  dbdata:
  uploads: