services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        uid: 1000
    ports:
      - "127.0.0.1:8000:80"
    volumes:
      - ./src:/var/www/html

  mysql:
    image: mysql
    ports:
      - "127.0.0.1:6033:3306"
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: app_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass

  phpmyadmin:
    image: phpmyadmin:latest
    links:
      - "mysql"
    ports:
      - "127.0.0.1:8081:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1

volumes:
  dbdata: